2021-08-02 14:37:46 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-08-02 14:39:25 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-08-02 14:39:28 ERROR CassandraUtil:21 - Method threw exception: java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-08-02 14:39:28 WARN  CassandraUtil:23 - java.base/java.lang.Thread.run(Thread.java:831)
2021-08-02 17:36:51 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-08-02 17:36:54 ERROR CassandraUtil:21 - Method threw exception: java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-08-02 17:36:54 WARN  CassandraUtil:23 - java.base/java.lang.Thread.run(Thread.java:831)
2021-08-02 17:39:56 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-08-02 17:39:57 ERROR CassandraUtil:21 - Method threw exception: com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra.us-west-1.amazonaws.com/18.144.158.97:9142, hostId=null, hashCode=1fd92acc): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node cassandra.us-west-1.amazonaws.com/18.144.158.97:9142: server replied with 'Provided username KyleBricker and/or password are incorrect' to AuthResponse request]
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:773)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.<init>(CassandraUtil.java:19)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.getInstance(CassandraUtil.java:31)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.revature.data.UserDAO.<init>(UserDAO.java:12)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.revature.services.UserService.<init>(UserService.java:11)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.revature.controllers.UserController.<init>(UserController.java:15)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.revature.Driver.javalin(Driver.java:42)
2021-08-02 17:39:57 WARN  CassandraUtil:23 - com.revature.Driver.main(Driver.java:14)
2021-08-02 17:40:39 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-08-02 17:40:41 ERROR CassandraUtil:21 - Method threw exception: com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra.us-west-1.amazonaws.com/18.144.158.97:9142, hostId=null, hashCode=99c1c2f): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node cassandra.us-west-1.amazonaws.com/18.144.158.97:9142: server replied with 'Provided username KyleBricker and/or password are incorrect' to AuthResponse request]
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:773)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.<init>(CassandraUtil.java:19)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.getInstance(CassandraUtil.java:31)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.revature.data.UserDAO.<init>(UserDAO.java:12)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.revature.services.UserService.<init>(UserService.java:11)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.revature.controllers.UserController.<init>(UserController.java:15)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.revature.Driver.javalin(Driver.java:42)
2021-08-02 17:40:41 WARN  CassandraUtil:23 - com.revature.Driver.main(Driver.java:14)
2021-08-02 17:42:35 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-08-02 17:42:37 ERROR CassandraUtil:21 - Method threw exception: com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra.us-west-1.amazonaws.com/18.144.158.92:9142, hostId=null, hashCode=99c1c2f): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node cassandra.us-west-1.amazonaws.com/18.144.158.92:9142: server replied with 'Provided username kylejbricker@yahoo.com and/or password are incorrect' to AuthResponse request]
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:773)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.<init>(CassandraUtil.java:19)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.getInstance(CassandraUtil.java:31)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.revature.data.UserDAO.<init>(UserDAO.java:12)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.revature.services.UserService.<init>(UserService.java:11)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.revature.controllers.UserController.<init>(UserController.java:15)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.revature.Driver.javalin(Driver.java:42)
2021-08-02 17:42:37 WARN  CassandraUtil:23 - com.revature.Driver.main(Driver.java:14)
2021-08-02 17:52:29 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-08-02 17:52:31 ERROR CassandraUtil:21 - Method threw exception: com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra.us-west-1.amazonaws.com/18.144.158.96:9142, hostId=null, hashCode=99c1c2f): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node cassandra.us-west-1.amazonaws.com/18.144.158.96:9142: server replied with 'Provided username KyleBricker and/or password are incorrect' to AuthResponse request]
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:773)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.<init>(CassandraUtil.java:19)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.revature.util.CassandraUtil.getInstance(CassandraUtil.java:31)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.revature.data.UserDAO.<init>(UserDAO.java:12)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.revature.services.UserService.<init>(UserService.java:11)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.revature.controllers.UserController.<init>(UserController.java:15)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.revature.Driver.javalin(Driver.java:42)
2021-08-02 17:52:31 WARN  CassandraUtil:23 - com.revature.Driver.main(Driver.java:14)
2021-08-02 17:53:16 TRACE CassandraUtil:16 - Establishing connection with Cassandra
